#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const readline = require('readline');

// Check if we're running in dry-run mode
const isDryRun = process.argv.includes('--dry-run') || process.argv.includes('-d');

// Create readline interface
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

// Ask a question and return a promise
function askQuestion(question) {
  return new Promise((resolve) => {
    if (isDryRun) {
      // In dry-run mode, just return the default value
      console.log(question);
      resolve('');
    } else {
      rl.question(question, (answer) => {
        resolve(answer);
      });
    }
  });
}

// Main configuration wizard function
async function runConfigWizard() {
  console.log('🏥 Hospital Management System - Configuration Wizard');
  console.log('==================================================');
  
  if (isDryRun) {
    console.log('Running in dry-run mode (no .env file will be created)');
  }
  
  console.log('This wizard will help you set up your environment variables.');
  console.log('');

  // Check if .env.example exists
  const envExamplePath = path.join(process.cwd(), '.env.example');
  const envPath = path.join(process.cwd(), '.env');
  
  if (!fs.existsSync(envExamplePath)) {
    console.error('❌ .env.example file not found in the current directory');
    process.exit(1);
  }

  // Read .env.example content
  const envExampleContent = fs.readFileSync(envExamplePath, 'utf8');
  
  // Parse the .env.example to extract variable names and descriptions
  const lines = envExampleContent.split('\n');
  const config = {};
  let currentComment = '';

  for (const line of lines) {
    if (line.startsWith('#')) {
      currentComment = line.substring(1).trim(); // Remove # and trim
    } else if (line.includes('=')) {
      const [key] = line.split('=', 1);
      if (key.trim()) {
        config[key.trim()] = {
          comment: currentComment,
          defaultValue: line.substring(line.indexOf('=') + 1).replace(/"/g, '').trim()
        };
        currentComment = '';
      }
    }
  }

  console.log('📋 Found the following environment variables to configure:');
  console.log('');

  const envVars = {};
  
  // Process each configuration variable
  for (const [key, value] of Object.entries(config)) {
    console.log(`\n📝 ${key}`);
    if (value.comment) {
      console.log(`   ${value.comment}`);
    }
    
    let defaultValue = value.defaultValue;
    if (defaultValue && !defaultValue.startsWith('your-')) {
      // Mask sensitive values
      if (key.toLowerCase().includes('secret') || key.toLowerCase().includes('password') || key.toLowerCase().includes('key')) {
        defaultValue = '********';
      }
    }
    
    if (defaultValue && !isDryRun) {
      const userInput = await askQuestion(`   Current/Default value: ${defaultValue}\n   Enter new value (or press Enter to keep current): `);
      envVars[key] = userInput || value.defaultValue;
    } else if (!isDryRun) {
      const userInput = await askQuestion(`   Enter value: `);
      envVars[key] = userInput;
    } else {
      // In dry-run mode, just show what would be asked
      console.log(`   Current/Default value: ${defaultValue}`);
      envVars[key] = value.defaultValue;
    }
  }

  // Generate .env file content
  let envContent = '# Environment variables for Hospital Management System\n';
  envContent += '# Generated by configuration wizard\n';
  envContent += '# Update these values according to your environment\n\n';
  
  for (const [key, value] of Object.entries(config)) {
    // Add comment if available
    if (value.comment) {
      envContent += `# ${value.comment}\n`;
    }
    // Add the variable with quotes for safety
    envContent += `${key}="${envVars[key] || value.defaultValue}"\n\n`;
  }

  if (!isDryRun) {
    // Write the .env file
    fs.writeFileSync(envPath, envContent);
    
    console.log('\n✅ Configuration completed successfully!');
    console.log(`📄 .env file has been created at: ${envPath}`);
    console.log('');
    console.log('💡 Remember to restart your development server for changes to take effect.');
  } else {
    console.log('\n✅ Dry-run completed! Here is what the .env file would contain:');
    console.log('\n' + '='.repeat(50));
    console.log(envContent);
    console.log('='.repeat(50));
    console.log('\n(Dry-run mode - no file was created)');
  }
  
  rl.close();
}

// Run the wizard
runConfigWizard().catch((error) => {
  console.error('❌ An error occurred:', error);
  process.exit(1);
});